### ISSUE TITLE
Add examples to public items and methods

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#17]
[Relevant API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-example)

Add examples to public items in this crate. Examples should be nice and simple, making the documentation prose concrete through code.

For some more details about writing documentation tests, see [this section of the Rust book](https://doc.rust-lang.org/book/first-edition/documentation.html#documentation-as-tests)

**Comment by steveklabnik** [comment]
This has been completed.
