### ISSUE TITLE
Add html_root_url attribute to crate root

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#19]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-html-root)

Add the `html_root_url` attribute to the `lib.rs` file that points to `"https://docs.rs/semver_parser/MAJOR.MINOR.PATCH"`. Also add a note to the `Cargo.toml` to remember to update this value when publishing a new version of the crate.

If we're expecting the next release to be `1.0.0` then we can probably just put that version in the `html_root_url` attribute.

**Comment by stanciuadrian** [comment]
I tried opening `https://docs.rs/semver_parser/0.7.0` in the browser but it tells me the requested crate does not exist. Did you mean `https://docs.rs/semver-parser/MAJOR.MINOR.PATCH` ?

**Comment by KodrAus** [comment]
Ah whoops, I mixed up those pesky `-` vs `_` characters. It should be `semver-parser`.

**Comment by steveklabnik** [comment]
This is no longer needed, closing!
