### ISSUE TITLE
Make structures with public fields non-exhaustive

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#20]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-private)

This one doesn't fit exactly into a guideline we've already got. `semver_parser` has passive datastructures. That is, structures that don't implement behaviour or have invariants to satisfy across fields. Having public fields makes sense here, but because users can exhaustively match on those fields in patterns we can't add any new ones without a major breaking change.

We can win back some of this flexibility by adding a private field (like `_private: ()`) to the following types:

- `Predicate`
- `VersionReq`
- `Version`

There is another drawback of doing this though: external users can't construct these types without using the `parse` functions, which might make unit testing a bit more difficult.

I think we need to discuss this a little more and decide whether it's a path we want to go down.

# Mentoring instructions

Leave a comment here on the thread and we'll work out how to get started.

**Comment by steveklabnik** [comment]
Given that the semver spec is released, and this follows the spec, I am okay with this being exhaustive. 👍

**Comment by KodrAus** [comment]
That seems reasonable to me :+1:
