### ISSUE TITLE
Add documentation to the crate root and public items

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#23]
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-crate-doc)

Also related to #17 

[An introduction to Rust documentation from the Book](https://doc.rust-lang.org/book/first-edition/documentation.html#documentation)

We should add some documentation to the `semver_parser` crate so when folks come across it they know what the crate is for, how to use it, and whether they're actually looking for `semver` or something else at a higher level instead.

Let's brainstorm some more concrete things we expect to get out of `semver_parser`s documentation. Do we want details of SemVer itself, like the `semver` docs have? Do we want a grammar for the parser?

**Comment by steveklabnik** [comment]
This has been completed.
