### ISSUE TITLE
Lack of rigorous tests for how to handle whitespace

### ISSUE THREAD

**Issue by udoprog** [steveklabnik/semver-parser#32]
The current parser for `VersionReq` doesn't accept whitespace in the middle of version requirements, like this: `> 0. 1`, `> 0.0. 1`.

There currently are no test-cases to enforce this behavior.

**Comment by steveklabnik** [comment]
In general, there could be a lot more test cases; I'd like to see if I can port node's test suite over.

**Comment by opilar** [comment]
@steveklabnik I can port node-semver tests
https://github.com/npm/node-semver/tree/master/test

Do we need all of them?

**Comment by opilar** [comment]
I didn't find any node-semver tests with spaces near dots.

**Comment by steveklabnik** [comment]
> Do we need all of them?

Ideally I'd like to know if/how we fail any of them. I'm not saying that we need to make them all pass, but I'd hope that we do.

**Comment by opilar** [comment]
@steveklabnik I can check. I think it's not relevant to the current topic. We can do this in another issue.

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
