### ISSUE TITLE
Borrow pre-release identifiers

### ISSUE THREAD

**Issue by udoprog** [steveklabnik/semver-parser#33]
The current parser always copies pre-release identifiers.

Pre-release identifiers include `ubuntu` and `alpha1` in constructs like these: `1.0.0-ubuntu.alpha1`.

The pre-release identifiers are stored in a way which doesn't permit borrowing here:
https://github.com/steveklabnik/semver-parser/blob/master/src/version.rs#L114

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
