### ISSUE TITLE
Excellent end-user error messages

### ISSUE THREAD

**Issue by udoprog** [steveklabnik/semver-parser#37]
The current error messages that can be formatted are a bit dry. They could be better!

While the current implementation is OK for `fmt::Debug`, the following could be improved for `fmt::Display`:

* `UnexpectedToken` could include a collection of expected tokens, and include helpful examples of what to change.
* `MoreInput` could simply format the rest of the string that that was unexpected. This would require the lexer to include spans (start and end offsets).

See: https://github.com/steveklabnik/semver-parser/blob/master/src/parser.rs#L92

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
