### ISSUE TITLE
Remove `From<Error<'input>> for String`

### ISSUE THREAD

**Issue by udoprog** [steveklabnik/semver-parser#38]
See: https://github.com/steveklabnik/semver-parser/blob/master/src/parser.rs#L103

This impl is present because documentation examples include `String` as a `Err` variant of `Result` heavily.

Examples:
 * https://github.com/steveklabnik/semver-parser/blob/master/src/version.rs#L13
 * https://github.com/steveklabnik/semver-parser/blob/master/src/version.rs#L50
 * https://github.com/steveklabnik/semver-parser/blob/master/src/version.rs#L128

These should be replaced with `Error`.

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
