### ISSUE TITLE
integer overflow causes panic

### ISSUE THREAD

**Issue by comex** [steveklabnik/semver-parser#4]
A version number like "18446744073709551616.0.0" will pass the regex but fail to parse as a u64, causing `version::parse` to panic in one of the `unwrap` calls (rather than returning an error).

**Comment by coder543** [comment]
Is there any way we can fix this? Experimentally, I've created a fork of semver-parser that uses `BigUint` extensively, and it works, but it does break API compatibility.

We could also consider just switching to u128 when that becomes stable, I suppose.

**Comment by coder543** [comment]
However, I guess this is just a brute-force solution that avoids the real issue at hand, which is that integer overflow causes a panic. Fixing the panic itself and providing a nice error message would be pretty simple.

**Comment by steveklabnik** [comment]
>  Fixing the panic itself and providing a nice error message would be pretty simple.

Yes, that's what my plan is here. I don't think we'll be using bigints here.
