### ISSUE TITLE
VersionReq::parse defaults to Compatible instead of Ex

### ISSUE THREAD

**Issue by hoodie** [steveklabnik/semver-parser#40]
when you parse a versionreq without `Op` the `Op` will be `Op::Compatible`. Shouldn't it be `Op::Ex` ? 

https://play.rust-lang.org/?gist=7cea996806a945503d65e321a38214ae&version=stable

**Comment by hoodie** [comment]
alright, I just saw this is intentional in the [doc](https://docs.rs/semver/0.9.0/semver/struct.VersionReq.html#examples-1), not sure if this is what most people would interpret this as though

**Comment by steveklabnik** [comment]
Every once in a while, someone is surprised, but this is the behavior that we want, for sure. Thanks!
