### ISSUE TITLE
Information in parse error is not actionable

### ISSUE THREAD

**Issue by kornelski** [steveklabnik/semver-parser#44]
`semver_parser::parser::Error` contains the token that was rejected, but doesn't have the location of the token. 

Without the location I can't recover from the error (e.g. if `MoreInput` had a position, it'd be easy to recover by trimming the excess characters).

There are crates published on crates.io with versions that can't be parsed with `semver-parser` ([e.g.](https://crates.io/crates/bootloader_precompiled) [e.g.](https://crates.io/crates/rthrift) [e.g.](https://crates.io/crates/helix) [e.g.](https://crates.io/crates/sassers) [e.g.](https://crates.io/crates/rustyline-nightly)), so I need the error recovery capability.

**Comment by k0pernicus** [comment]
Hi @kornelski,

I am working on a solution for your issue (submitted a long time ago...), still in WiP.  
Do not hesitate to take part of the discussion if you are still interested by a solution: https://github.com/steveklabnik/semver-parser/pull/58.

**Comment by k0pernicus** [comment]
I removed the "WiP" tag to propose a first solution (with unit tests).  
Feel free to comment: #58

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
