### ISSUE TITLE
Support `Display`

### ISSUE THREAD

**Issue by epage** [steveklabnik/semver-parser#45]
I'm working on a bin that needs to programmatically manipulate `VersionReq`, requiring me to use semver_parser instead of semver.  Unfortunately, semver is what owns the Display logic so I'm having to copy/paste it into my crate.

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
