### ISSUE TITLE
Consider reducing number of dependencies

### ISSUE THREAD

**Issue by matklad** [steveklabnik/semver-parser#49]
I haven't looked into this yet, but I am a bit concerned about the tree of deps here:

```
│   ├── semver v0.11.0
│   │   ├── semver-parser v0.10.0
│   │   │   ├── pest v2.1.3
│   │   │   │   └── ucd-trie v0.1.3
│   │   │   └── pest_derive v2.1.0
│   │   │       ├── pest v2.1.3 (*)
│   │   │       └── pest_generator v2.1.3
│   │   │           ├── pest v2.1.3 (*)
│   │   │           ├── pest_meta v2.1.3
│   │   │           │   ├── maplit v1.0.2
│   │   │           │   └── pest v2.1.3 (*)
│   │   │           │   [build-dependencies]
│   │   │           │   └── sha-1 v0.8.2
│   │   │           │       ├── block-buffer v0.7.3
│   │   │           │       │   ├── block-padding v0.1.5
│   │   │           │       │   │   └── byte-tools v0.3.1
│   │   │           │       │   ├── byte-tools v0.3.1
│   │   │           │       │   ├── byteorder v1.3.4
│   │   │           │       │   └── generic-array v0.12.3
│   │   │           │       │       └── typenum v1.12.0
│   │   │           │       ├── digest v0.8.1
│   │   │           │       │   └── generic-array v0.12.3 (*)
│   │   │           │       ├── fake-simd v0.1.2
│   │   │           │       └── opaque-debug v0.2.3
│   │   │           ├── proc-macro2 v1.0.24 (*)
│   │   │           ├── quote v1.0.7 (*)
│   │   │           └── syn v1.0.45 (*)
│   │   └── serde v1.0.117 (*)
```

**Comment by steveklabnik** [comment]
I am actually re-writing the semver crate entirely and it will have zero dependencies. So, I am in support of this idea, but also don't need to keep an issue open for it. Thanks!

**Comment by matklad** [comment]
Note that this issue currently blocks updating cargo-metada in rust-analyzer. I have a feeling that rewrite might not be finished too soon, so, in the meantime, merging #50 and releasing `0.11.1` would help.

Alternatively, I guess I can ask cargo-metadata to revert upgrade to `0.11`.

**Comment by steveklabnik** [comment]
I would generally encourage cargo_metadata to stick to the same version of semver as cargo itself; i have not tried to update cargo with the latest versions of semver. i don't *expect* there to be drift between versions, but also haven't taken time to actually verify (other than our test suite) that that's the case. 

Yes, there's no actual timeline for the re-write. I'm getting there, but I'm not guaranteeing a date, so you're doing the right thing for sure.

If we can sort the question in #50 , I'd be happy to cut a .1.

**Comment by matklad** [comment]
Yeah, I'll submit `cargo metadata` patch to revert then. I kind of think that either #50 or yanking semver 0.11might be a good idea. 

Sorry for a little to direct tone here -- I was just to unpleasantly surprised by the update to rust-analyzer's lockfile due to what seemed to be an uninteresting dependency upgrade.

**Comment by steveklabnik** [comment]
It's all good. I am also annoyed because I really care about semver's compile time, and part of me switching to pest for this series was that the compile times seemed very small to me.
