### ISSUE TITLE
Parsing an empty string yields a wildcard

### ISSUE THREAD

**Issue by LPGhatguy** [steveklabnik/semver-parser#51]
Parsing a `RangeSet` from an empty string results in a wildcard match instead of an error. This seems strange to me!

Repro using `semver::VersionReq`, which defers to this type I believe: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dae7604c0fbe269a0cd43788fab3f32d

Parsing from strings that are entirely spaces also results in a wildcard range set, but other whitespace characters result in errors.

## Context
I'm working on a package manager. Before adopting semver's `VersionReq` type, I had a test case that looked like this:

```rust
// Requirements missing versions should not parse
PackageReq::parse("foo/bar@").unwrap_err();
```

The type is parsed by finding a name, then `/`, another name, `@`, then defers to `VersionReq`'s `FromStr` implementation. I peeked at the semver crate's code and wound up here.

**Comment by steveklabnik** [comment]
This matches the behavior of other implementations, like npm, and is intentional. Thank you though!
