### ISSUE TITLE
build error on rustfmt::skip

### ISSUE THREAD

**Issue by dwarburt** [steveklabnik/semver-parser#53]
Today I had a build error while trying to build the brave browser

       Compiling semver-parser v0.10.1
    error[E0658]: non-builtin inner attributes are unstable
     --> /home/david/git/fork/brave-browser/src/brave/build/rustup/0.1.4/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
      |
    4 | #![rustfmt::skip]
      | ^^^^^^^^^^^^^^^^^
      |
      = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information
    
       Compiling tracing-log v0.1.1
    error: aborting due to previous error
    
    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `semver-parser`.
    
    
It seems like that comes from this line: https://github.com/steveklabnik/semver-parser/blob/4ad3c7b10496d0007af2f327cb50a9897b5b969f/tests/genpest.rs#L17 but in order to get it to build I had to delete this line https://github.com/steveklabnik/semver-parser/blob/4ad3c7b10496d0007af2f327cb50a9897b5b969f/src/generated.rs#L4  from my local working copy, and after that it builds fine.

**Comment by steveklabnik** [comment]
dup of 52

**Comment by dwarburt** [comment]
oops, sorry not sure how I double posted this when I was trying to clean up the formatting.

**Comment by steveklabnik** [comment]
It's all good! I would rather get two issues than zero issues :)
