### ISSUE TITLE
0.10 makes this difficult to manipulate user version strings

### ISSUE THREAD

**Issue by epage** [steveklabnik/semver-parser#57]
`semver` is the high level crate.  `semver-parser` 0.9 was a low level parsing crate that made it easy (minus #45) to programmatically modify a version range, like `cargo-release` needs to do for `Cargo.toml` files.  Unfortunately, `semver-parser` 0.10 has morphed this into a intermediate level crate that does post-processing on the parsed data to normalize it, losing how the original version range was specified and making it more work to turn a range into something that can be put back into a `Cargo.toml` file.

Can the lower level API be exposed, in addition to the new normalizing API?

**Comment by steveklabnik** [comment]
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982
