### ISSUE TITLE
Hex compat

### ISSUE THREAD

**Issue by lpil** [steveklabnik/semver-parser#61]
Hello! Thanks for this very nice library.

I'm looking to use this the [Gleam language](https://github.com/gleam-lang/gleam/) build tool, which uses the Erlang package manager Hex.
It uses semver but there are some subtly different behaviours for version requirements.

`1.0.0` means `=1.0.0`, similar to npm

`~>` has a slightly different meaning to in Cargo

~> | Translation
-- | --
~> 2.0.0 | >= 2.0.0 and < 2.1.0
~> 2.1.2 | >= 2.1.2 and < 2.2.0
~> 2.1.3-dev | >= 2.1.3-dev and < 2.2.0
~> 2.0 | >= 2.0.0 and < 3.0.0
~> 2.1 | >= 2.1.0 and < 3.0.0

`^` is not permitted.

Source: https://hexdocs.pm/elixir/Version.html#module-requirements

I believe this behaviour may also be compatible with RubyGems, but I am unsure.

Would you accept a pull request adding support for a Hex compat mode?

Cheers,
Louis

**Comment by steveklabnik** [comment]
> Would you accept a pull request adding support for a Hex compat mode?

Not right this moment, but maybe eventually. The reason why is that I'm (very slowly) re-working the internals of the semver package. Thanks for raising this!

**Comment by lpil** [comment]
Good to know, thanks. Do you have a recommendation for how I might approach this in the meantime? Perhaps fork the existing version or the new in-development version?

No worries if not :)

**Comment by lpil** [comment]
Gunna make a new lib, thank you
