### ISSUE TITLE
Please derive PartialOrd for Op (and WildcardVersion)

### ISSUE THREAD

**Issue by joshtriplett** [steveklabnik/semver-parser#9]
This would allow sorting a list of predicates by operator, which helps if you want to canonicalize a version requirement to check it against a pattern (for instance, "is this a range, >= x and < y")

**Comment by steveklabnik** [comment]
I am not opposed to this 👍

**Comment by connorkuehl** [comment]
Is the [default derive](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#derivable) behavior acceptable in this case?

**Comment by joshtriplett** [comment]
Yeah, any reasonable order works.

**Comment by steveklabnik** [comment]
closed by https://github.com/steveklabnik/semver-parser/commit/240ada67e4e8a0578b9a52d4062f961005c6060a
